<section class="elementor-section elementor-top-section elementor-element elementor-element-2ddc3ce animated-slow elementor-section-boxed elementor-section-height-default elementor-section-height-default animated fadeIn" data-id="2ddc3ce" data-element_type="section" data-settings="{&quot;animation&quot;:&quot;fadeIn&quot;}">
    <div class="elementor-container elementor-column-gap-default">
        <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-d8b5a5b" data-id="d8b5a5b" data-element_type="column">
            <div class="elementor-widget-wrap elementor-element-populated">
                <div class="elementor-element elementor-element-378dc8a elementor-widget elementor-widget-slider_revolution" data-id="378dc8a" data-element_type="widget" data-widget_type="slider_revolution.default">
                    <div class="elementor-widget-container">

                        <div class="wp-block-themepunch-revslider">

                            <sr7-module data-alias="slider-1" data-id="1" id="SR7_1_1" class="rs-ov-hidden" data-version="6.7.31" style="height: 795px; touch-action: pan-y; cursor: pointer; user-select: none;" data-current="2">
                                <sr7-adjuster style="height: 795px; touch-action: pan-y;"></sr7-adjuster>
                                <sr7-content style="height: 795px; left: -20px; touch-action: pan-y; width: 1280px; top: 0px;">
                                    <sr7-slide id="SR7_1_1-1" data-key="1" style="touch-action: pan-y; pointer-events: auto; visibility: visible; display: block; z-index: 2;">




                                        <sr7-mask style="overflow: visible; min-height: auto; min-width: auto; width: 100%; height: 795px; z-index: 0; position: absolute; display: block; visibility: visible; left: 0px; top: 0px;"><sr7-bg id="SR7_1_1-1-6" class="sr7-layer " style="touch-action: pan-y; padding: 0px; width: 100%; height: 795px; display: block; visibility: visible; overflow: hidden; pointer-events: none; opacity: 1; background: transparent;" data-type="shape" data-subtype="slidebg"><canvas width="2560" height="1590" style="width: 1280px; height: 795px; z-index: 1; position: absolute; top: 0px; left: 0px; background: transparent;" class="sr7-a-canvas"></canvas><canvas width="2560" height="1590" style="width: 1280px; height: 795px; z-index: 1; position: absolute; top: 0px; left: 0px; visibility: visible; background: transparent; opacity: 1;"></canvas><noscript style="touch-action: pan-y;"><img decoding="async" src="https://themes.codcrash.com/CMS/CC07/wp-content/uploads/2024/02/sliderimg-01.jpg" alt="" title="sliderimg-01"></noscript></sr7-bg></sr7-mask><sr7-txt id="SR7_1_1-1-2" class="sr7-layer " style="touch-action: pan-y; font-family: &quot;Cormorant Garamond&quot;; font-size: 90px; font-weight: 600; color: rgb(239, 238, 222); text-transform: uppercase; text-decoration: none; letter-spacing: 1px; line-height: 86px; text-align: center; white-space: nowrap; overflow: visible; padding: 0px; width: auto; height: auto; z-index: 7; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 318px; top: 243px; translate: none; rotate: none; scale: none; visibility: visible; opacity: 1; transform: translate(0px, 0px); pointer-events: auto; background: transparent;"> biggest art’s <br style="touch-action: pan-y;">
                                            gallery</sr7-txt><sr7-txt id="SR7_1_1-1-3" class="sr7-layer " style="touch-action: pan-y; font-family: Sora; font-size: 16px; font-weight: 400; color: rgb(239, 238, 222); text-transform: none; text-decoration: none; letter-spacing: 0px; line-height: 25px; text-align: left; white-space: nowrap; overflow: visible; padding: 0px; width: auto; height: auto; z-index: 8; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 505px; top: 167px; translate: none; rotate: none; scale: none; visibility: visible; opacity: 1; transform: translate(0px, 0px); pointer-events: auto; background: transparent;">Welcome To World's Best Gallery</sr7-txt><sr7-btn id="SR7_1_1-1-5" class="sr7-btn sr7-layer" style="font-family: Sora; font-size: 14px; font-weight: 500; color: rgb(239, 238, 222); text-transform: none; text-decoration: none; letter-spacing: 0px; line-height: 50px; text-align: center; white-space: normal; overflow: visible; padding: 0px; min-height: 0px; width: 180px; height: auto; z-index: 9; border-radius: 29px; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 540px; top: 470px; translate: none; rotate: none; scale: none; visibility: visible; opacity: 1; transform: translate(0px, 0px); pointer-events: auto; background: rgb(172, 131, 77);"> Read More</sr7-btn></sr7-slide>
                                    <sr7-slide id="SR7_1_1-2" data-key="2" style="touch-action: pan-y; z-index: 5; pointer-events: auto; visibility: visible; display: block;">




                                        <sr7-mask style="overflow: visible; min-height: auto; min-width: auto; width: 100%; height: 795px; z-index: 0; position: absolute; display: block; visibility: visible; left: 0px; top: 0px;"><sr7-bg id="SR7_1_1-2-6" class="sr7-layer " style="touch-action: pan-y; padding: 0px; width: 100%; height: 795px; display: block; visibility: visible; overflow: hidden; pointer-events: none; opacity: 1; background: transparent;" data-type="shape" data-subtype="slidebg"><canvas width="2560" height="1590" style="width: 1280px; height: 795px; z-index: 1; position: absolute; top: 0px; left: 0px; background: transparent;" class="sr7-a-canvas"></canvas><canvas width="2560" height="1590" style="width: 1280px; height: 795px; z-index: 1; position: absolute; top: 0px; left: 0px; visibility: hidden; background: transparent; opacity: 1;"></canvas><noscript style="touch-action: pan-y;"><img decoding="async" src="https://themes.codcrash.com/CMS/CC07/wp-content/uploads/2024/03/sliderimg-02.jpg" alt="" title="sliderimg-02"></noscript></sr7-bg></sr7-mask><sr7-txt id="SR7_1_1-2-0" class="sr7-layer " style="touch-action: pan-y; font-family: &quot;Cormorant Garamond&quot;; font-size: 90px; font-weight: 600; color: rgb(239, 238, 222); text-transform: uppercase; text-decoration: none; letter-spacing: 1px; line-height: 86px; text-align: center; white-space: nowrap; overflow: visible; padding: 0px; width: auto; height: auto; z-index: 7; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 318px; top: 243px; translate: none; rotate: none; scale: none; visibility: hidden; opacity: 0; transform: scale(0.9, 0.9); pointer-events: none; background: transparent;"> biggest art’s <br style="touch-action: pan-y;">
                                            gallery</sr7-txt><sr7-txt id="SR7_1_1-2-3" class="sr7-layer " style="touch-action: pan-y; font-family: Sora; font-size: 16px; font-weight: 400; color: rgb(239, 238, 222); text-transform: none; text-decoration: none; letter-spacing: 0px; line-height: 25px; text-align: left; white-space: nowrap; overflow: visible; padding: 0px; width: auto; height: auto; z-index: 8; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 505px; top: 167px; translate: none; rotate: none; scale: none; visibility: hidden; opacity: 0; transform: scale(0.9, 0.9); pointer-events: none; background: transparent;">Welcome To World's Best Gallery</sr7-txt><sr7-btn id="SR7_1_1-2-5" class="sr7-btn sr7-layer" style="font-family: Sora; font-size: 14px; font-weight: 500; color: rgb(239, 238, 222); text-transform: none; text-decoration: none; letter-spacing: 0px; line-height: 50px; text-align: center; white-space: normal; overflow: visible; padding: 0px; min-height: 0px; width: 180px; height: auto; z-index: 9; border-radius: 29px; position: absolute; vertical-align: top; transform-origin: 50% 50%; display: block; left: 540px; top: 470px; translate: none; rotate: none; scale: none; visibility: hidden; opacity: 0; transform: scale(0.9, 0.9); pointer-events: none; background: rgb(172, 131, 77);"> Read More</sr7-btn></sr7-slide>
                                    <sr7-slide id="SR7_1_1-3" data-key="3" class="sr7-staticslide sr7-staticslide-high" style="pointer-events: none; touch-action: pan-y; display: block; visibility: visible;">
                                    </sr7-slide>
                                    <sr7-module-shadow class="sr7-shdw-0" style="touch-action: pan-y;"></sr7-module-shadow></sr7-content>

                            </sr7-module>
                            <script>
                                SR7.PMH ??={}; SR7.PMH["SR7_1_1"] = {cn:100,state:false,fn: function() { if (_tpt!==undefined && _tpt.prepareModuleHeight !== undefined) {  _tpt.prepareModuleHeight({id:"SR7_1_1",el:[795,795,700,600,500],type:'standard',shdw:'0',gh:[795,795,700,600,500],gw:[1240,1240,1024,778,480],vpt:['-100px&#039;,&#039;-100px&#039;,&#039;-100px&#039;,&#039;-100px&#039;,&#039;-100px'],size:{fullWidth:true, fullHeight:false},mh:'0',onh:0,onw:0,bg:{color:'{"orig":"transparent","type":"solid","string":"transparent"}'}});   SR7.PMH["SR7_1_1"].state=true;} else if(SR7.PMH["SR7_1_1"].cn-->0)	setTimeout( SR7.PMH["SR7_1_1"].fn,19);}};SR7.PMH["SR7_1_1" ].fn();
                            </script>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
